// constants.js
export const SIZES = ['Small', 'Medium', 'Large', 'Huge'];

export const SRD_LANGUAGES = [
  'Common', 'Dwarvish', 'Elvish', 'Giant', 'Gnomish', 'Goblin', 'Halfling', 
  'Orc', 'Abyssal', 'Celestial', 'Draconic', 'Deep Speech', 'Infernal', 
  'Primordial', 'Sylvan', 'Undercommon'
];

export const SRD_SKILLS = [
  'Acrobatics', 'Animal Handling', 'Arcana', 'Athletics', 'Deception', 
  'History', 'Insight', 'Intimidation', 'Investigation', 'Medicine', 
  'Nature', 'Perception', 'Performance', 'Persuasion', 'Religion', 
  'Sleight of Hand', 'Stealth', 'Survival'
];

export const SRD_ACTIONS = [
  { name: 'Bite', type: 'Natural Weapon', damage: '1d6 piercing', useStr: true },
  { name: 'Claw', type: 'Natural Weapon', damage: '1d4 slashing', useStr: true },
  { name: 'Gore', type: 'Natural Weapon', damage: '1d8 piercing', useStr: true },
  { name: 'Greataxe', type: 'Melee Weapon Attack', damage: '1d12 slashing', useStr: true },
  { name: 'Greatsword', type: 'Melee Weapon Attack', damage: '2d6 slashing', useStr: true },
  { name: 'Heavy Crossbow', type: 'Ranged Weapon Attack', damage: '1d10 piercing', useDex: true },
  { name: 'Light Crossbow', type: 'Ranged Weapon Attack', damage: '1d8 piercing', useDex: true },
  { name: 'Longbow', type: 'Ranged Weapon Attack', damage: '1d8 piercing', useDex: true },
  { name: 'Longsword', type: 'Melee Weapon Attack', damage: '1d8 slashing', useStr: true },
  { name: 'Shortsword', type: 'Melee Weapon Attack', damage: '1d6 piercing', useDex: true },
  { name: 'Shortbow', type: 'Ranged Weapon Attack', damage: '1d6 piercing', useDex: true },
  { name: 'Slam', type: 'Natural Weapon', damage: '1d6 bludgeoning', useStr: true },
  { name: 'Sting', type: 'Natural Weapon', damage: '1d4 piercing', useDex: true },
  { name: 'Tail', type: 'Natural Weapon', damage: '1d6 bludgeoning', useStr: true },
  { name: 'Tentacle', type: 'Natural Weapon', damage: '1d6 bludgeoning', useStr: true }
].sort((a, b) => a.name.localeCompare(b.name));

export const SRD_FEATURES = [
  { name: 'Amphibious', description: 'Can breathe air and water.' },
  { name: 'Blindsight', description: 'Can perceive its surroundings without relying on sight, within a specific radius.' },
  { name: 'Darkvision', description: 'Can see in darkness up to 60 feet.' },
  { name: 'Damage Transfer', description: 'When damaged, can transfer half the damage to a willing creature within range.' },
  { name: 'False Appearance', description: 'While motionless, is indistinguishable from a natural object.' },
  { name: 'Keen Senses', description: 'Has advantage on Wisdom (Perception) checks.' },
  { name: 'Light Sensitivity', description: 'Disadvantage on attack rolls and Wisdom (Perception) checks in bright light.' },
  { name: 'Magic Resistance', description: 'Advantage on saving throws against spells and magical effects.' },
  { name: 'Pack Tactics', description: 'Advantage on attack rolls against creatures if at least one ally is within 5 feet.' },
  { name: 'Regeneration', description: 'Regains hit points at the start of its turn.' },
  { name: 'Spider Climb', description: 'Can climb difficult surfaces, including upside down, without making an ability check.' },
  { name: 'Spellcasting', description: 'The creature is a spellcaster.' },
  { name: 'Standing Leap', description: 'Its long jump is up to 30 feet and its high jump is up to 15 feet, with or without a running start.' },
  { name: 'Telekinetic', description: 'YOu can cast mage hand freely as a cantrip without verbal or material components.' },
  { name: 'Undead Fortitude', description: 'If damage reduces it to 0 hit points, must make a Constitution saving throw to drop to 1 hit point instead.' }
].sort((a, b) => a.name.localeCompare(b.name));

export const FEATURE_POINT_OPTIONS = [
  {
    id: 'action',
    name: 'Additional Action/Reaction/Bonus Action',
    cost: 1,
    type: 'action',
    description: 'Add one ability, action, reaction, or bonus action'
  },
  {
    id: 'damage',
    name: 'Secondary Damage Type or Double Damage',
    cost: 1,
    type: 'damage',
    description: 'Add a secondary damage type or ability to an existing attack; or double the damage of an existing attack'
  },
  {
    id: 'movement',
    name: 'Additional Movement',
    cost: 1,
    type: 'movement',
    description: 'Add Burrow, Swim, Climb, or Fly Speed equal to movement; or add ten feet of additional speed',
    options: ['Burrow', 'Swim', 'Climb', 'Fly', '+10 ft to existing']
  }
].sort((a, b) => {
  // Sort by cost first
  if (a.cost !== b.cost) {
    return a.cost - b.cost;
  }
  // Then alphabetically by name
  return a.name.localeCompare(b.name);
});

export const SRD_ARMOR = [
  { name: 'Natural Armor', ac: 10 },
  { name: 'Leather', ac: 11 },
  { name: 'Studded Leather', ac: 12 },
  { name: 'Hide', ac: 12 },
  { name: 'Chain Shirt', ac: 13 },
  { name: 'Scale Mail', ac: 14 },
  { name: 'Breastplate', ac: 14 },
  { name: 'Half Plate', ac: 15 },
  { name: 'Ring Mail', ac: 14 },
  { name: 'Chain Mail', ac: 16 },
  { name: 'Splint', ac: 17 },
  { name: 'Plate', ac: 18 }
].sort((a, b) => a.name.localeCompare(b.name));

export const MOVEMENT_TYPES = ['Walk', 'Fly', 'Swim', 'Burrow', 'Climb'];

export const SIZE_MOVEMENT = {
  Small: 20,
  Medium: 30,
  Large: 40,
  Huge: 50
};

export const CR_TABLE = [
  { minAC: 13, minHP: 71, maxHP: 85, cr: 1 },
  { minAC: 13, minHP: 86, maxHP: 100, cr: 2 },
  { minAC: 13, minHP: 101, maxHP: 115, cr: 3 },
  { minAC: 14, minHP: 116, maxHP: 130, cr: 4 },
  { minAC: 15, minHP: 131, maxHP: 145, cr: 5 },
  { minAC: 15, minHP: 146, maxHP: 160, cr: 6 },
  { minAC: 15, minHP: 161, maxHP: 175, cr: 7 },
  { minAC: 16, minHP: 176, maxHP: 190, cr: 8 },
  { minAC: 16, minHP: 191, maxHP: 205, cr: 9 },
  { minAC: 17, minHP: 206, maxHP: 220, cr: 10 },
  { minAC: 17, minHP: 221, maxHP: 235, cr: 11 },
  { minAC: 17, minHP: 236, maxHP: 250, cr: 12 },
  { minAC: 18, minHP: 251, maxHP: 265, cr: 13 },
  { minAC: 18, minHP: 266, maxHP: 280, cr: 14 },
  { minAC: 18, minHP: 281, maxHP: 295, cr: 15 },
  { minAC: 18, minHP: 296, maxHP: 310, cr: 16 },
  { minAC: 19, minHP: 311, maxHP: 325, cr: 17 },
  { minAC: 19, minHP: 326, maxHP: 340, cr: 18 },
  { minAC: 19, minHP: 341, maxHP: 355, cr: 19 },
  { minAC: 19, minHP: 356, maxHP: 400, cr: 20 },
  { minAC: 19, minHP: 401, maxHP: 445, cr: 21 },
  { minAC: 19, minHP: 446, maxHP: 490, cr: 22 },
  { minAC: 19, minHP: 491, maxHP: 535, cr: 23 },
  { minAC: 19, minHP: 536, maxHP: 580, cr: 24 },
  { minAC: 19, minHP: 581, maxHP: 625, cr: 25 },
  { minAC: 19, minHP: 626, maxHP: 670, cr: 26 },
  { minAC: 19, minHP: 671, maxHP: 715, cr: 27 },
  { minAC: 19, minHP: 716, maxHP: 760, cr: 28 },
  { minAC: 19, minHP: 760, maxHP: 805, cr: 29 },
  { minAC: 19, minHP: 805, maxHP: 850, cr: 30 }
];

// constants/effect-types.js
export const DAMAGE_TYPES = [
  'acid',
  'cold',
  'fire',
  'force',
  'lightning',
  'necrotic',
  'poison',
  'psychic',
  'radiant',
  'thunder',
  'nonmagical bludgeoing/slashing/piercing'
];

export const CONDITIONS = [
  'blinded',
  'charmed',
  'deafened',
  'frightened',
  'grappled',
  'incapacitated',
  'paralyzed',
  'petrified',
  'poisoned',
  'prone',
  'restrained',
  'stunned',
  'unconscious'
];

export const FULL_SPELL_LIST = [
  {"name": "Acid Arrow","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Acid Splash","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Aid","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Alarm","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Alter Self","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Animal Friendship","school": "Enchantment","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Animal Messenger","school": "Enchantment","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Animal Shapes","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Animate Dead","school": "Necromancy","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Animate Objects","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Antilife Shell","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Antimagic Field","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Antipathy/Sympathy","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Arcane Eye","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Arcane Hand","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Arcane Lock","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Arcane Sword","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Arcanist's Magic Aura","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Astral Projection","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Augury","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Awaken","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Bane","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Banishment","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Barkskin","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Beacon of Hope","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": true,"controls_creatures": false},
  {"name": "Bestow Curse","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Black Tentacles","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Blade Barrier","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Bless","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Blight","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Blindness/Deafness","school": "Necromancy","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Blink","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Blur","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Branding Smite","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Burning Hands","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Call Lightning","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Calm Emotions","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Chain Lightning","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Charm Person","school": "Enchantment","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Chill Touch","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Circle of Death","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Clairvoyance","school": "Divination","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Clone","school": "Necromancy","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Cloudkill","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Color Spray","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Command","school": "Enchantment","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Commune","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Commune With Nature","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Comprehend Languages","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Compulsion","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Cone of Cold","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Confusion","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Conjure Animals","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Conjure Celestial","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Conjure Elemental","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Conjure Fey","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Conjure Minor Elementals","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Conjure Woodland Beings","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Contact Other Plane","school": "Divination","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": true,"controls_creatures": false},
  {"name": "Contagion","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Contingency","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Continual Flame","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Control Water","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Control Weather","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Counterspell","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Create Food and Water","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Create or Destroy Water","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Create Undead","school": "Necromancy","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Creation","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Cure Wounds","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Dancing Lights","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Darkness","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Darkvision","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Daylight","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Death Ward","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": true,"provides_healing": false,"controls_creatures": false},
  {"name": "Delayed Blast Fireball","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Demiplane","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Detect Evil and Good","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Detect Magic","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Detect Poison and Disease","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Detect Thoughts","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Dimension Door","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Disguise Self","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Disintegrate","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Dispel Evil and Good","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Dispel Magic","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Divination","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Divine Favor","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Divine Word","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Dominate Beast","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Dominate Monster","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Dominate Person","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Dream","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Druidcraft","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Earthquake","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Eldritch Blast","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Enhance Ability","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Enlarge/Reduce","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Entangle","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Enthrall","school": "Enchantment","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Etherealness","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Expeditious Retreat","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Eyebite","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Fabricate","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Faerie Fire","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Faithful Hound","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "False Life","school": "Necromancy","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Fear","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Feather Fall","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Feeblemind","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": true,"controls_creatures": false},
  {"name": "Find Familiar","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Find Steed","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Find the Path","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Find Traps","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Finger of Death","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Fire Bolt","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Fire Shield","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": true,"provides_healing": false,"controls_creatures": false},
  {"name": "Fire Storm","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Fireball","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Flame Blade","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Flame Strike","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Flaming Sphere","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Flesh to Stone","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Floating Disk","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Fly","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Fog Cloud","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Forbiddance","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Forcecage","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Foresight","school": "Divination","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Freedom of Movement","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Freezing Sphere","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Gaseous Form","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": true,"provides_healing": false,"controls_creatures": true},
  {"name": "Gate","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Geas","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": true,"controls_creatures": true},
  {"name": "Gentle Repose","school": "Necromancy","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Giant Insect","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Glibness","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Globe of Invulnerability","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Glyph of Warding","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Goodberry","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Grease","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Greater Invisibility","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Greater Restoration","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Guardian of Faith","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": true,"provides_healing": false,"controls_creatures": false},
  {"name": "Guards and Wards","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Guidance","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Guiding Bolt","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Gust of Wind","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Hallow","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": true,"provides_healing": false,"controls_creatures": true},
  {"name": "Hallucinatory Terrain","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Harm","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Haste","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Heal","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Healing Word","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Heat Metal","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Hellish Rebuke","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Heroes' Feast","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Heroism","school": "Enchantment","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Hideous Laughter","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Hold Monster","school": "Enchantment","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Hold Person","school": "Enchantment","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Holy Aura","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Hunter's Mark","school": "Divination","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Hypnotic Pattern","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Ice Storm","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Identify","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Illusory Script","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Imprisonment","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Incendiary Cloud","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Inflict Wounds","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Insect Plague","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Instant Summons","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Invisibility","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Irresistible Dance","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Jump","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Knock","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Legend Lore","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Lesser Restoration","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Levitate","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Light","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Lightning Bolt","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Locate Animals or Plants","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Locate Creature","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Locate Object","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Longstrider","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Mage Armor","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Mage Hand","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Magic Circle","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Magic Jar","school": "Necromancy","source": "Unknown","causes_damage": false,"prevents_damage": true,"provides_healing": false,"controls_creatures": false},
  {"name": "Magic Missile","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Magic Mouth","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Magic Weapon","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Magnificent Mansion","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Major Image","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Mass Cure Wounds","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": true,"controls_creatures": false},
  {"name": "Mass Heal","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": true,"controls_creatures": false},
  {"name": "Mass Healing Word","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": true,"controls_creatures": false},
  {"name": "Mass Suggestion","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Maze","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Meld Into Stone","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Mending","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Message","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Meteor Swarm","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Mind Blank","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Minor Illusion","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Mirage Arcane","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Mirror Image","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Mislead","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Misty Step","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Modify Memory","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": true,"controls_creatures": true},
  {"name": "Moonbeam","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Move Earth","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Nondetection","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Pass Without Trace","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Passwall","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Phantasmal Killer","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Phantom Steed","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Planar Ally","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Planar Binding","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Plane Shift","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Plant Growth","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Poison Spray","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Polymorph","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Power Word Kill","school": "Enchantment","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Power Word Stun","school": "Enchantment","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Prayer of Healing","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Prestidigitation","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Prismatic Spray","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Prismatic Wall","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Private Sanctum","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Produce Flame","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Programmed Illusion","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Project Image","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Protection From Energy","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": true,"provides_healing": false,"controls_creatures": false},
  {"name": "Protection from Evil and Good","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": true,"provides_healing": false,"controls_creatures": true},
  {"name": "Protection from Poison","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": true,"provides_healing": false,"controls_creatures": false},
  {"name": "Purify Food and Drink","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Raise Dead","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Ray of Enfeeblement","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Ray of Frost","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Regenerate","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": true,"controls_creatures": true},
  {"name": "Reincarnate","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Remove Curse","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Resilient Sphere","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Resistance","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Resurrection","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Reverse Gravity","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Revivify","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Rope Trick","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Sacred Flame","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Sanctuary","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Scorching Ray","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Scrying","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Secret Chest","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "See Invisibility","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Seeming","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Sending","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Sequester","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Shapechange","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Shatter","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Shield","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Shield of Faith","school": "Abjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Shillelagh","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Shocking Grasp","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Silence","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Silent Image","school": "Illusion","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Simulacrum","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Sleep","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Sleet Storm","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Slow","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Spare the Dying","school": "Necromancy","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Speak with Animals","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Speak with Dead","school": "Necromancy","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Speak with Plants","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Spider Climb","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Spike Growth","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Spirit Guardians","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Spiritual Weapon","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Stinking Cloud","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Stone Shape","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Stoneskin","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": true,"provides_healing": false,"controls_creatures": false},
  {"name": "Storm of Vengeance","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Suggestion","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Sunbeam","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Sunburst","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Symbol","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Telekinesis","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Telepathic Bond","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Teleport","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Teleportation Circle","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Thaumaturgy","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Thunderwave","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Time Stop","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Tiny Hut","school": "Evocation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Tongues","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Transport via Plants","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Tree Stride","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "True Polymorph","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "True Resurrection","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "True Seeing","school": "Divination","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "True Strike","school": "Divination","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Unseen Servant","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": true},
  {"name": "Vampiric Touch","school": "Necromancy","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": true,"controls_creatures": false},
  {"name": "Vicious Mockery","school": "Enchantment","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Wall of Fire","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Wall of Force","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Wall of Ice","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Wall of Stone","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Wall of Thorns","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Warding Bond","school": "Abjuration","source": "Unknown","causes_damage": true,"prevents_damage": true,"provides_healing": false,"controls_creatures": false},
  {"name": "Water Breathing","school": "Transmutation","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Water Walk","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Web","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Weird","school": "Illusion","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Wind Walk","school": "Transmutation","source": "Unknown","causes_damage": true,"prevents_damage": true,"provides_healing": false,"controls_creatures": false},
  {"name": "Wind Wall","school": "Evocation","source": "Unknown","causes_damage": true,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Wish","school": "Conjuration","source": "Unknown","causes_damage": true,"prevents_damage": true,"provides_healing": true,"controls_creatures": false},
  {"name": "Word of Recall","school": "Conjuration","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false},
  {"name": "Zone of Truth","school": "Enchantment","source": "Unknown","causes_damage": false,"prevents_damage": false,"provides_healing": false,"controls_creatures": false}
  ]

  export const LEGENDARYACTIONS = []

  export const SPELLCASTERLEVELS = [
    {"cr": 1, "level": 3},
    {"cr": 2, "level": 4},
    {"cr": 3, "level": 5},
    {"cr": 4, "level": 5},
    {"cr": 5, "level": 6},
    {"cr": 6, "level": 7},
    {"cr": 7, "level": 7},
    {"cr": 8, "level": 8},
    {"cr": 9, "level": 9},
    {"cr": 10, "level": 9},
    {"cr": 11, "level": 10},
    {"cr": 12, "level": 11},
    {"cr": 13, "level": 11},
    {"cr": 14, "level": 12},
    {"cr": 15, "level": 13},
    {"cr": 16, "level": 13},
    {"cr": 17, "level": 14},
    {"cr": 18, "level": 15},
    {"cr": 19, "level": 15},
    {"cr": 20, "level": 16},
    {"cr": 21, "level": 17},
    {"cr": 22, "level": 17},
    {"cr": 23, "level": 18},
    {"cr": 24, "level": 19},
    {"cr": 25, "level": 19},
    {"cr": 26, "level": 20}
  ]